version: "3"
services:
  pm2:
    image: keymetrics/pm2:latest-alpine
    volumes:
      - ./:/src
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    command: ["pm2-runtime", "start", "/src/api/pm2.json"]