version: "3"
services:
  pm2:
    image: keymetrics/pm2:latest-alpine
    volumes:
      - ./api:/api
      - ./conf/pm2.json:/pm2.json
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: ["pm2-runtime", "start", "pm2.json"]
